import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Providers } from "@/redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="ja">
        <body className={inter.className}>
          <header className="w-full">
            <div className="mx-auto px-5 w-full max-w-7xl">
              <div className="flex items-center justify-between">
                <div className="">Test App</div>
                <div className="flex items-center justify-between">
                  <Link href="posts">Posts</Link>
                </div>
              </div>
            </div>
          </header>
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
        </body>
      </html>
    </Providers>
  );
}
